version: '3'

services:
    producer:
        build: producer
        environment:
            - SQS_QUEUE_URL=<sqs queue url here>
            - SQS_MESSAGE_GROUP_ID=consumer
            - SLEEP_SECONDS=0.5
            - AWS_DEFAULT_REGION=eu-central-1
            - AWS_ACCESS_KEY_ID=<access key here>
            - AWS_SECRET_ACCESS_KEY=<secret key here>
    consumer:
        build: consumer
        environment:
            - SQS_QUEUE_URL=<sqs queue url here>
            - SLEEP_SECONDS=1
            - AWS_DEFAULT_REGION=eu-central-1
            - AWS_ACCESS_KEY_ID=<access key here>
            - AWS_SECRET_ACCESS_KEY=<secret key here>
