apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: consumer
          image: csuvikg/kedaexample:producer
          env:
            - name: SQS_QUEUE_URL
              value: 'https://sqs.eu-central-1.amazonaws.com/517406932026/consumer_queue.fifo'
            - name: SQS_MESSAGE_GROUP_ID
              value: 'consumer'
            - name: SLEEP_SECONDS
              value: '2'
            - name: AWS_DEFAULT_REGION
              value: 'eu-central-1'
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: aws_access_key_id
                  optional: false
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: aws_secret_access_key
                  optional: false
